development:
  secret_key_base: 6f7fa4fd2aa1d6eac293b06dc03e387d433e2cfce73a1d5c44c18da00a28138def4fa5292103b8e941027e4d0c76c1264b1b43f898d2b270e842847822e7451f
  twitter:
      consumer_key: secret
      consumer_secret: secret
  sso:
    user: secret
    password: secret
  xtenit:
    username: secret
    password: secret
  mailgun:
    port: 587
    address: smtp.mailgun.org
    authentication: plain
    api_key: key-secret
    public_key: pubkey-secret
    domain: domain-secret

test:
  secret_key_base: 354e3422520b8245c4bdd5f485cc3bb15181d02a374ac41aba86e4e7baad33209585ec81b93d22c653b87c74913031dee15787c83f03dc075ae652cd34b7fe67

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
